package vote

// Code generated by "weaver generate". DO NOT EDIT.
import (
	"context"
	"fmt"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"github.com/google/uuid"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
	"time"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/eminetto/microservices-serviceweaver/vote/VoteComponent",
		Iface: reflect.TypeOf((*VoteComponent)(nil)).Elem(),
		New:   func() any { return &Service{} },
		LocalStubFn: func(impl any, tracer trace.Tracer) any {
			return voteComponent_local_stub{impl: impl.(VoteComponent), tracer: tracer}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return voteComponent_client_stub{stub: stub, storeMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/eminetto/microservices-serviceweaver/vote/VoteComponent", Method: "Store"})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return voteComponent_server_stub{impl: impl.(VoteComponent), addLoad: addLoad}
		},
	})
}

// Local stub implementations.

type voteComponent_local_stub struct {
	impl   VoteComponent
	tracer trace.Tracer
}

func (s voteComponent_local_stub) Store(ctx context.Context, a0 Vote) (r0 uuid.UUID, err error) {
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "vote.VoteComponent.Store", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Store(ctx, a0)
}

// Client stub implementations.

type voteComponent_client_stub struct {
	stub         codegen.Stub
	storeMetrics *codegen.MethodMetrics
}

func (s voteComponent_client_stub) Store(ctx context.Context, a0 Vote) (r0 uuid.UUID, err error) {
	// Update metrics.
	start := time.Now()
	s.storeMetrics.Count.Add(1)

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "vote.VoteComponent.Store", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
		err = s.stub.WrapError(err)

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
			s.storeMetrics.ErrorCount.Add(1)
		}
		span.End()

		s.storeMetrics.Latency.Put(float64(time.Since(start).Microseconds()))
	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	(a0).WeaverMarshal(enc)
	var shardKey uint64

	// Call the remote method.
	s.storeMetrics.BytesRequest.Put(float64(len(enc.Data())))
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	if err != nil {
		return
	}
	s.storeMetrics.BytesReply.Put(float64(len(results)))

	// Decode the results.
	dec := codegen.NewDecoder(results)
	dec.DecodeBinaryUnmarshaler(&r0)
	err = dec.Error()
	return
}

// Server stub implementations.

type voteComponent_server_stub struct {
	impl    VoteComponent
	addLoad func(key uint64, load float64)
}

// GetStubFn implements the stub.Server interface.
func (s voteComponent_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Store":
		return s.store
	default:
		return nil
	}
}

func (s voteComponent_server_stub) store(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 Vote
	(&a0).WeaverUnmarshal(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Store(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.EncodeBinaryMarshaler(&r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

// AutoMarshal implementations.

var _ codegen.AutoMarshal = &Vote{}

func (x *Vote) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Vote.WeaverMarshal: nil receiver"))
	}
	enc.EncodeBinaryMarshaler(&x.ID)
	enc.String(x.Email)
	enc.String(x.TalkName)
	enc.Int(x.Score)
}

func (x *Vote) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Vote.WeaverUnmarshal: nil receiver"))
	}
	dec.DecodeBinaryUnmarshaler(&x.ID)
	x.Email = dec.String()
	x.TalkName = dec.String()
	x.Score = dec.Int()
}
